---

variables:
  ARTIFACTORY_DEV_URL: '<pypi-repo-url-dev>'
  ARTIFACTORY_PRD_URL: '<pypi-repo-url-stable>'

stages:
  - lint
  - test
  - evaluate
  - build
  - deploy

.on_prd:
  image: python:3.9-slim
  tags:
    - environment-prd

lint:
  stage: lint
  extends:
    - .on_prd
  script:
    - flake8
    - isort --check .

pytest:
  stage: test
  image: python:3.9-slim
  script:
    - pip3 install -r requirements.txt
    - pytest
  tags:
    - environment-prd

evaluate-tag:
  stage: evaluate
  extends:
    - .on_prd
  script: python3 ./gcip/script_library/evaluate_version_scheme.py
  rules:
    - if: $CI_COMMIT_TAG

build:
  stage: build
  extends:
    - .on_prd
  script: python3 setup.py bdist_wheel
  artifacts:
    paths:
      - dist/

pages:
  stage: build
  extends:
    - .on_prd
  script:
    - pip install -r docs/requirements.txt
    - sphinx-build -b html -E -a docs public/${CI_COMMIT_REF_NAME}
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "sphinx"'

.deploy-to-artifactory:
  stage: deploy
  extends:
    - .on_prd
  script: python3 -m twine upload --non-interactive --disable-progress-bar dist/*

deploy-to-dev-artifactory:
  extends:
    - .deploy-to-artifactory
  variables:
    TWINE_REPOSITORY_URL: $ARTIFACTORY_DEV_URL
    TWINE_USERNAME: $ARTIFACTORY_DEV_USER
    TWINE_PASSWORD: $ARTIFACTORY_DEV_PASSWORD
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_REF_NAME == "master"
      when: on_success

deploy-to-prd-artifactory:
  extends:
    - .deploy-to-artifactory
  variables:
    TWINE_REPOSITORY_URL: $ARTIFACTORY_PRD_URL
    TWINE_USERNAME: $ARTIFACTORY_PRD_USER
    TWINE_PASSWORD: $ARTIFACTORY_PRD_PASSWORD
  rules:
    - if: $CI_COMMIT_TAG
