---
variables:
  GCIP_VERSION: "0.0.$CI_PIPELINE_ID"

generate-pipeline:
  stage: build
  image: python:3.9-slim
  script:
    - pip3 install -r requirements.txt
    - python3 .gitlab-ci.py > generated-config.yml
  artifacts:
    paths:
      - generated-config.yml
  tags:
    - environment-prd

run-pipeline:
  stage: deploy
  needs:
    - generate-pipeline
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-pipeline
    strategy: depend
