---
generate-pipeline:
  stage: build
  image: thomass/gcip
  script:
    - pip3 install -r requirements.txt
    - python3 .gitlab-ci.py
  artifacts:
    paths:
      - generated-config.yml

run-pipeline:
  stage: deploy
  needs:
    - generate-pipeline
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-pipeline
    strategy: depend
