---
variables:
  CUSTOM_GCIP_VERSION: "0.4.0"
  CUSTOM_CDK_VERSION: "0.0.$CI_PIPELINE_ID"

include:
  - project: otherproject/custom-gcip-library
    file: custom-gcip-pipeline.yml

trigger_custom_gcip_library:
  stage: .post
  trigger:
    project: otherproject/custom-gcip-library
    branch: master
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_REF_NAME == "master"
      when: on_success
