stages:
- lint
- test
- execute
lint-isort:
  image:
    name: python:3.9-slim
  stage: lint
  script:
  - pip3 install --upgrade isort
  - isort --check .
lint-flake8:
  image:
    name: python:3.9-slim
  stage: lint
  script:
  - pip3 install --upgrade flake8
  - flake8
test-pytest:
  image:
    name: python:3.9-slim
  stage: test
  script:
  - pip3 install --upgrade -v -r requirements.txt
  - pytest
test-evaluate-git-tag-pep404-conformity:
  image:
    name: thomass/gcip:0.3.0
  stage: test
  script:
  - python3 -m gcip.tools.evaluate_git_tag_pep404_conformity
  rules:
  - if: $CI_COMMIT_TAG
    when: on_success
    allow_failure: false
execute-kaniko:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint:
    - ''
  stage: execute
  script:
  - mkdir -p /kaniko/.docker && echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"$DOCKER_USER\",\"password\":\"$DOCKER_LOGIN\"}}}"
    > /kaniko/.docker/config.json
  - date
  - executor --no-push --destination thomass/gcip
  - rm -rf /kaniko/.docker/config.json
