name: Documenation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdoc3
        gem install asciidoctor
    - name: Create User Documentation
      run: |
        mkdir -p docs/api
        pdoc3 --html -f --skip-errors --output-dir docs/api gcip
        asciidoctor docs/index.adoc -o docs/index.html
        asciidoctor docs/user/index.adoc -o docs/user/index.html
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        folder: docs
